version: "3.7"
services:
  zadanie.backend:
    build:
      args:
        user: zadanie
        uid: ${WWWUSER}
      context: ./
      dockerfile: Dockerfile
    image: zadanie
    container_name: zadanie-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - zadanie

  db:
    image: mysql:8.0
    container_name: zadanie-db
    restart: unless-stopped
    ports:
    - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./storage/mysql-data:/var/lib/mysql
    networks:
      - zadanie

  nginx:
    image: nginx:alpine
    container_name: zadanie-nginx
    restart: unless-stopped
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx:/etc/nginx/conf.d/
    networks:
      - zadanie

networks:
  zadanie:
    driver: bridge